const express=require('express');
const mongoose=require('mongoose');
const Schema=mongoose.Schema;

const UserSchema=new Schema({
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true
    },
    password:{
        type:String,
        required:false,
        trim:true
    },
    name:{
        type:String,
        required:false
    },
    Phone:{
        type:Number,
        required:false,
        unique:true
    },
    Role:{
        type:String,
        enum:["admin","member"],
        default:"member"
    },
    avatarUrl:{
        type:String,
        required:false
    },
    lastLogin:{
        type:Date,

    },
    department:{
        type:String,
        required:false
    },
    joinDate:{
        type:Date,
        required:false
    },
    location:{
        type:String,
        required:false
    },
    bio:{
        type:String,
        required:false
    },
    skills:[{
        type:String,
        required:false
    }],
    age:{
        type:Number,
        required:false
    },
    workinghours:{
        days:[{
            type:String,
            required:false
        }],
        starttime:{
            type:String,
            required:false
        },
        endtime:{
            type:String,
            required:false
        },
    },
    coverImage:{
        type:String,
        required:true
    },
}, {timestamps:true});
module.exports=mongoose.model('users',UserSchema);